# 完整脚本：稳健解析 PTEN 突变，输出合法突变与被删除记录（含原因）
# 依赖包：openxlsx, stringr, dplyr, tidyr, writexl
# 安装（如缺失）：
# install.packages(c("openxlsx","stringr","dplyr","tidyr","writexl"))

library(openxlsx)
library(stringr)
library(dplyr)
library(tidyr)
library(writexl)

# ---------- 1. PTEN 蛋白序列（请勿更改除非你确实要用别的序列） ----------
#sequence <- "MTAIIKEIVSRNKRRYQEDGFDLDLTYIYPNIIAMGFPAERLEGVYRNNIDDVVRFLDSKHKNHYKIYNLCAERHYDTAKFNCRVAQYPFEDHNPPQLELIKPFCEDLDQWLSEDDNHVAAIHCKAGKGRTGVMICAYLLHRGKFLKAQEALDFYGEVRTRDKKGVTIPSQRRYVYYYSYLLKNHLDYRPVALLFHKMMFETIPMFSGGTCNPQFVVCQLKVKIYSSNSGPTRREDKFMYFEFPQPLPVCGDIKVEFFHKQNKMLKKDKMFHFWVNTFFIPGPEETSEKVENGSLCDQEIDSICSIERADNDKEYLVLTLTKNDLDKANKDKANRYFSPNFKVKLYFTKTVEEPSNPEASSSTSVTPDVSDNEPDHYRYSDTTDSDPENEPFDEDQHTQITKV"
#sequence <- "MTSRRWFHPNITGVEAENLLLTRGVDGSFLARPSKSNPGDFTLSVRRNGAVTHIKIQNTGDYYDLYGGEKFATLAELVQYYMEHHGQLKEKNGDVIELKYPLNCADPTSERWFHGHLSGKEAEKLLTEKGKHGSFLVRESQSHPGDFVLSVRTGDDKGESNDGKSKVTHVMIRCQELKYDVGGGERFDSLTDLVEHYKKNPMVETLGTVLQLKQPLNTTRINAAEIESRVRELSKLAETTDKVKQGFWEEFETLQQQECKLLYSRKEGQRQENKNKNRYKNILPFDHTRVVLHDGDPNEPVSDYINANIIMPEFETKCNNSKPKKSYIATQGCLQNTVNDFWRMVFQENSRVIVMTTKEVERGKSKCVKYWPDEYALKEYGVMRVRNVKESAAHDYTLRELKLSKVGQGNTERTVWQYHFRTWPDHGVPSDPGGVLDFLEEVHHKQESIMDAGPVVVHCSAGIGRTGTFIVIDILIDIIREKGVDCDIDVPKTIQMVRSQRSGMVQTEAQYRFIYMAVQHYIETLQRRIEEEQKSKRKGHEYTNIKYSLADQTSGDQSPLPPCTPTPPCAEMREDSARVYENVGLMQQQKSFR"
#sequence <- 'MTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQVVIDGETCLLDILDTAGQEEYSAMRDQYMRTGEGFLCVFAINNTKSFEDIHHYREQIKRVKDSEDVPMVLVGNKCDLPSRTVDTKQAQDLARSYGIPFIETSAKTRQRVEDAFYTLVREIRQYRLKKISKEEKTPGCVKIKKCIIM'
#sequence <- 'MTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQVVIDGETCLLDILDTAGQEEYSAMRDQYMRTGEGFLCVFAINNTKSFEDIHHYREQIKRVKDSEDVPMVLVGNKCDLPSRTVDTKQAQDLARSYGIPFIETSAKTRQGVDDAFYTLVREIRKHKEKMSKDGKKKKKKSKTKCVIM'
#sequence <- "MAALSGGGGGGAEPGQALFNGDMEPEAGAGAGAAASSAADPAIPEEVWNIKQMIKLTQEHIEALLDKFGGEHNPPSIYLEAYEEYTSKLDALQQREQQLLESLGNGTDFSVSSSASMDTVTSSSSSSLSVLPSSLSVFQNPTDVARSNPKSPQKPIVRVFLPNKQRTVVPARCGVTVRDSLKKALMMRGLIPECCAVYRIQDGEKKPIGWDTDISWLTGEELHVEVLENVPLTTHNFVRKTFFTLAFCDFCRKLLFQGFRCQTCGYKFHQRCSTEVPLMCVNYDQLDLLFVSKFFEHHPIPQEEASLAETALTSGSSPSAPASDSIGPQILTSPSPSKSIPIPQPFRPADEDHRNQFGQRDRSSSAPNVHINTIEPVNIDDLIRDQGFRGDGGSTTGLSATPPASLPGSLTNVKALQKSPGPQRERKSSSSSEDRNRMKTLGRRDSSDDWEIPDGQITVGQRIGSGSFGTVYKGKWHGDVAVKMLNVTAPTPQQLQAFKNEVGVLRKTRHVNILLFMGYSTKPQLAIVTQWCEGSSLYHHLHIIETKFEMIKLIDIARQTAQGMDYLHAKSIIHRDLKSNNIFLHEDLTVKIGDFGLATVKSRWSGSHQFEQLSGSILWMAPEVIRMQDKNPYSFQSDVYAFGIVLYELMTGQLPYSNINNRDQIIFMVGRGYLSPDLSKVRSNCPKAMKRLMAECLKKKRDERPLFPQILASIELLARSLPKIHRSASEPSLNRAGFQTEDFSLYACASPKTPIQAGGYGAFPVH"
#sequence <- "MPKKKPTPIQLNPAPDGSAVNGTSSAETNLEALQKKLEELELDEQQRKRLEAFLTQKQKVGELKDDDFEKISELGAGNGGVVFKVSHKPSGLVMARKLIHLEIKPAIRNQIIRELQVLHECNSPYIVGFYGAFYSDGEISICMEHMVIKGLTYLREKHKIMHRDVKPSNILVNSRGEIKLCDFGVSGQLIDSMANSFVGTRSYMSPERLQGTHYSVQSDIWSMGLSLVEMAVGRYPIPPPDAKELELMFGCQVEGDAAETPPRPRTPGRPLSSYGMDSRPPMAIFELLDYIVNEPPPKLPSGVFSLEFQDFVNKCLIKNPAERADLKQLMVHAFIKRSDAEEVDFAGWLCSTIGLNQPSTPTHAAGV"
#sequence <- 'MLARRKPVLPALTINPTIAEGPSPTSEGASEANLVDLQKKLEELELDEQQKKRLEAFLTQKAKVGELKDDDFERISELGAGNGGVVTKVQHRPSGLIMARKLIHLEIKPAIRNQIIRELQVLHECNSPYIVGFYGAFYSDGEISICMEHMDGGSLDQVLKEAKRIPEEILGKVSIAVLRGLAYLREKHQIMHRDVKPSNILVNSRGEIKLCDFGVSGQLIDSMANSFVGTRSYMAPERLQGTHYSVQSDIWSMGLSLVELAVGRYPIPPPDAKELEAIFGRPVVDGEEGEPHSISPRPRPPGRPVSGHGMDSRPAMAIFELLDYIVNEPPPKLPNGVFTPDFQEFVNKCLIKNPAERADLKMLTNHTFIKRSEVEEVDFAGWLCKTLRLNQPGTPTRTAV'
#sequence <- 'MPPRPSSGELWGIHLMPPRILVECLLPNGMIVTLECLREATLITIKHELFKEARKYPLHQLLQDESSYIFVSVTQEAEREEFFDETRRLCDLRLFQPFLKVIEPVGNREEKILNREIGFAIGMPVCEFDMVKDPEVQDFRRNILNVCKEAVDLRDLNSPHSRAMYVYPPNVESSPELPKHIYNKLDKGQIIVVIWVIVSPNNDKQKYTLKINHDCVPEQVIAEAIRKKTRSMLLSSEQLKLCVLEYQGKYILKVCGCDEYFLEKYPLSQYKYIRSCIMLGRMPNLMLMAKESLYSQLPMDCFTMPSYSRRISTATPYMNGETSTKSLWVINSALRIKILCATYVNVNIRDIDKIYVRTGIYHGGEPLCDNVNTQRVPCSNPRWNEWLNYDIYIPDLPRAARLCLSICSVKGRKGAKEEHCPLAWGNINLFDYTDTLVSGKMALNLWPVPHGLEDLLNPIGVTGSNPNKETPCLELEFDWFSSVVKFPDMSVIEEHANWSVSREAGFSYSHAGLSNRLARDNELRENDKEQLKAISTRDPLSEITEQEKDFLWSHRHYCVTIPEILPKLLLSVKWNSRDEVAQMYCLVKDWPPIKPEQAMELLDCNYPDPMVRGFAVRCLEKYLTDDKLSQYLIQLVQVLKYEQYLDNLLVRFLLKKALTNQRIGHFFFWHLKSEMHNKTVSQRFGLLLESYCRACGMYLKHLNRQVEAMEKLINLTDILKQEKKDETQKVQMKFLVEQMRRPDFMDALQGFLSPLNPAHQLGNLRLEECRIMSSAKRPLWLNWENPDIMSELLFQNNEIIFKNGDDLRQDMLTLQIIRIMENIWQNQGLDLRMLPYGCLSIGDCVGLIEVVRNSHTIMQIQCKGGLKGALQFNSHTLHQWLKDKNKGEIYDAAIDLFTRSCAGYCVATFILGIGDRHNSNIMVKDDGQLFHIDFGHFLDHKKKKFGYKRERVPFVLTQDFLIVISKGAQECTKTREFERFQEMCYKAYLAIRQHANLFINLFSMMLGSGMPELQSFDDIAYIRKTLALDKTEQEALEYFMKQMNDAHHGGWTTKMDWIFHTIKQHALN'
#sequence <- 'MEHIQGAWKTISNGFGFKDAVFDGSSCISPTIVQQFGYQRRASDDGKLTDPSKTSNTIRVFLPNKQRTVVNVRNGMSLHDCLMKALKVRGLQPECCAVFRLLHEHKGKKARLDWNTDAASLIGEELQVDFLDHVPLTTHNFARKTFLKLAFCDICQKFLLNGFRCQTCGYKFHEHCSTKVPTMCVDWSNIRQLLLFPNSTIGDSGVPALPSLTMRRMRESVSRMPVSSQHRYSTPHAFTFNTSSPSSEGSLSQRQRSTSTPNVHMVSTTLPVDSRMIEDAIRSHSESASPSALSSSPNNLSPTGWSQPKTPVPAQRERAPVSGTQEKNKIRPRGQRDSSYYWEIEASEVMLSTRIGSGSFGTVYKGKWHGDVAVKILKVVDPTPEQFQAFRNEVAVLRKTRHVNILLFMGYMTKDNLAIVTQWCEGSSLYKHLHVQETKFQMFQLIDIARQTAQGMDYLHAKNIIHRDMKSNNIFLHEGLTVKIGDFGLATVKSRWSGSQQVEQPTGSVLWMAPEVIRMQDNNPFSFQSDVYSYGIVLYELMTGELPYSHINNRDQIIFMVGRGYASPDLSKLYKNCPKAMKRLVADCVKKVKEERPLFPQILSSIELLQHSLPKINRSASEPSLHRAAHTEDINACTLTTSPRLPVF'
sequence <- 'MQAQQLPYEFFSEENAPKWRGLLVPALKKVQGQVHPTLESNDDALQYVEELILQLLNMLCQAQPRSASDVEERVQKSFPHPIDKWAIADAQSAIEKRKRRNPLSLPVEKIHPLLKEVLGYKIDHQVSVYIVAVLEYISADILKLVGNYVRNIRHYEITKQDIKVAMCADKVLMDMFHQDVEDINILSLTDEEPSTSGEQTYYDLVKAFMAEIRQYIRELNLIIKVFREPFVSNSKLFSANDVENIFSRIVDIHELSVKLLGHIEDTVEMTDEGSPHPLVGSCFEDLAEELAFDPYESYARDILRPGFHDRFLSQLSKPGAALYLQSIGEGFKEAVQYVLPRLLLAPVYHCLHYFELLKQLEEKSEDQEDKECLKQAITALLNVQSGMEKICSKSLAKRRLSESACRFYSQQMKGKQLAIKKMNEIQKNIDGWEGKDIGQCCNEFIMEGTLTRVGAKHERHIFLFDGLMICCKSNHGQPRLPGASNAEYRLKEKFFMRKVQINDKDDTNEYKHAFEIILKDENSVIFSAKSAEEKNNWMAALISLQYRSTLERMLDVTMLQEEKEEQMRLPSADVYRFAEPDSEENIIFEENMQPKAGIPIIKAGTVIKLIERLTYHMYADPNFVRTFLTTYRSFCKPQELLSLIIERFEIPEPEPTEADRIAIENGDQPLSAELKRFRKEYIQPVQLRVLNVCRHWVEHHFYDFERDAYLLQRMEEFIGTVRGKAMKKWVESITKIIQRKKIARDNGPGHNITFQSSPPTVEWHISRPGHIETFDLLTLHPIEIARQLTLLESDLYRAVQPSELVGSVWTKEDKEINSPNLLKMIRHTTNLTLWFEKCIVETENLEERVAVVSRIIEILQVFQELNNFNGVLEVVSAMNSSPVYRLDHTFEQIPSRQKKILEEAHELSEDHYKKYLAKLRSINPPCVPFFGIYLTNILKTEEGNPEVLKRHGKELINFSKRRKVAEITGEIQQYQNQPYCLRVESDIKRFFENLNPMGNSMEKEFTDYLFNKSLEIEPRNPKPLPRFPKKYSYPLKSPGVRPSNPRPGTMRHPTPLQQEPRKISYSRIPESETESTASAPNSPRTPLTPPPASGASSTTDVCSVFDSDHSSPFHSSNDTVFIQVTLPHGPRSASVSSISLTKGTDEVPVPPPVPPRRRPESAPAESSPSKIMSKHLDSPPAIPPRQPTSKAYSPRYSISDRTSISDPPESPPLLPPREPVRTPDVFSSSPLHLQPPPLGKKSDHGNAFFPNSPSPFTPPPPQTPSPHGTRRHLPSPPLTQEVDLHSIAGPPVPPRQSTSQHIPKLPPKTYKREHTHPSMHRDGPPLLENAHSS'
# ---------- 2. 读入 Excel（修改为你自己的文件路径） ----------
input_path  <- "C:\\毕业论文\\数据\\SOS1\\SOS1.xlsx"
out_filtered <- "C:\\毕业论文\\数据\\SOS1\\SOS1_submit_filtered.xlsx"
out_removed  <- "C:\\毕业论文\\数据\\SOS1\\SOS1_submit_removed.xlsx"

# 使用 openxlsx 读取（colNames = FALSE 以防首行是混合格式）
df_raw <- openxlsx::read.xlsx(input_path, colNames = FALSE)

# 基本检查
cat("读取文件：", input_path, "\n")
cat("读入行数：", nrow(df_raw), " 列数：", ncol(df_raw), "\n")

# 尝试命名前 3 列为常见含义（如果存在）
ncol_use <- ncol(df_raw)
names_to_assign <- c("Disease", "Mutation", "Category")
if (ncol_use >= 1) colnames(df_raw)[1] <- "Disease"
if (ncol_use >= 2) colnames(df_raw)[2] <- "Mutation"
if (ncol_use >= 3) colnames(df_raw)[3] <- "Category"

# 如果不确定哪列是真正的突变列，自动检测（根据能匹配突变模式的数量）
pattern_simple <- "[A-Za-z]\\d+[A-Za-z]"  # 用于检测的简单模式
if (!"Mutation" %in% colnames(df_raw)) {
  # 选出现 pattern 匹配数最多的列作为突变列
  counts <- sapply(df_raw, function(col) {
    sum(stringr::str_count(as.character(col), pattern_simple), na.rm = TRUE)
  })
  mutation_col_index <- which.max(counts)
  if (counts[mutation_col_index] > 0) {
    colnames(df_raw)[mutation_col_index] <- "Mutation"
    cat("自动识别突变列为第", mutation_col_index, "列（", colnames(df_raw)[mutation_col_index], "）。\n")
  } else {
    # 默认使用第2列（保持向后兼容）
    if (ncol_use >= 2) {
      colnames(df_raw)[2] <- "Mutation"
      cat("未能自动识别明显的突变列，默认使用第2列作为 Mutation。\n")
    } else {
      stop("表格列数少于2且无法识别 Mutation 列，请检查输入文件。")
    }
  }
}

# 将突变列转换为字符
df_raw$Mutation <- as.character(df_raw$Mutation)
df_raw$Disease  <- as.character(df_raw$Disease)
if ("Category" %in% colnames(df_raw)) df_raw$Category <- as.character(df_raw$Category)

# ---------- 3. 解析、展开（若单元格中有多个突变则拆开） ----------
# 提取的严格突变格式：单字母 + 数字 + 单字母（例如 A120E）
# 在单元格里可能存在多值，用分隔符 ; , / | 空格 等分隔
# 我们用正则从单元格中提取所有满足模式的子串
extract_mutations <- function(raw) {
  if (is.na(raw) || trimws(raw) == "") return(character(0))
  # 抽取所有形如 A120E 或 a120e 的片段
  hits <- stringr::str_extract_all(as.character(raw), "([A-Za-z]\\d+[A-Za-z])")[[1]]
  # 去除空与重复并返回大写标准化
  hits <- unique(hits)
  if (length(hits) == 0) return(character(0))
  hits <- toupper(stringr::str_replace_all(hits, "\\s+", ""))
  return(hits)
}

# 构建展开表：每行一个突变
df_expanded <- df_raw %>%
  mutate(.row_id = seq_len(n())) %>%
  rowwise() %>%
  mutate(.mut_list = list(extract_mutations(Mutation))) %>%
  ungroup() %>%
  select(.row_id, everything()) %>%
  unnest(.mut_list, keep_empty = TRUE) %>%
  rename(Mutation_parsed = .mut_list)

# 如果某些行没有解析出任何突变，Mutation_parsed 会为 NA/character(0) —— 下面处理
df_expanded$Mutation_parsed <- as.character(df_expanded$Mutation_parsed)

# ---------- 4. 检查每个解析后的突变是否与参考序列匹配 ----------
check_single_mutation <- function(mut, seq) {
  # 返回列表： valid(TRUE/FALSE) & reason 字符串 & parsed components
  out <- list(valid = FALSE, reason = NA_character_, wild = NA_character_, pos = NA_integer_, mutaa = NA_character_)
  if (is.na(mut) || trimws(mut) == "") {
    out$reason <- "NA_or_empty_parsed"
    return(out)
  }
  m <- toupper(trimws(mut))
  # 确保严格匹配完整格式，如 A120E
  mat <- stringr::str_match(m, "^([A-Z])(\\d+)([A-Z])$")
  if (is.na(mat[1,1])) {
    out$reason <- "pattern_mismatch_parsed"
    return(out)
  }
  wild <- mat[1,2]
  pos  <- as.numeric(mat[1,3])
  mutaa<- mat[1,4]
  
  out$wild <- wild
  out$pos  <- pos
  out$mutaa<- mutaa
  
  # 检查位置范围
  if (is.na(pos) || pos <= 0) {
    out$reason <- "invalid_position"
    return(out)
  }
  if (pos > nchar(seq)) {
    out$reason <- paste0("position_out_of_range(", pos, ">", nchar(seq), ")")
    return(out)
  }
  
  seq_res <- substr(seq, pos, pos)
  seq_res <- toupper(seq_res)
  if (seq_res == wild) {
    out$valid <- TRUE
    out$reason <- "ok"
  } else {
    out$reason <- paste0("wt_mismatch(seq_has_", seq_res, "_vs_given_", wild, ")")
  }
  return(out)
}

# 应用检查函数，得到列
check_res <- lapply(df_expanded$Mutation_parsed, check_single_mutation, seq = sequence)
check_df <- do.call(rbind, lapply(check_res, function(x) {
  data.frame(valid = x$valid, reason = x$reason, wild = x$wild, pos = x$pos, mutaa = x$mutaa, stringsAsFactors = FALSE)
}))

df_checked <- bind_cols(df_expanded, check_df)

# ---------- 5. 分离合法 / 非法，并输出文件 ----------
df_valid <- df_checked %>% filter(valid == TRUE)
df_invalid <- df_checked %>% filter(!(valid == TRUE))

# 如果某些原始行没有解析出突变（Mutation_parsed NA 或长度0），也会出现在 df_invalid 中，reason 会标注
cat("原始行数:", nrow(df_raw), "\n")
cat("展开后行数（解析出的突变条目数）:", nrow(df_expanded), "\n")
cat("合法突变条目数:", nrow(df_valid), "\n")
cat("被过滤/不合法条目数:", nrow(df_invalid), "\n\n")

# 保存合法突变（包含原始 Disease, 原始 Mutation 单元格，以及解析后的 Mutation_parsed 等信息）
if (nrow(df_valid) > 0) {
  # 选取常用列保存
  out_valid <- df_valid %>%
    select(.row_id, Disease, Mutation, Mutation_parsed, wild, pos, mutaa, Category, reason) %>%
    mutate(source_row = .row_id) %>%
    select(-.row_id)
  writexl::write_xlsx(out_valid, out_filtered)
  cat("已写出合法突变到：", out_filtered, "\n")
} else {
  cat("没有合法突变，未写出合法文件。\n")
}

# 保存被删除 / 不合法条目（含原因）
if (nrow(df_invalid) > 0) {
  out_invalid <- df_invalid %>%
    select(.row_id, Disease, Mutation, Mutation_parsed, wild, pos, mutaa, Category, reason) %>%
    mutate(source_row = .row_id) %>%
    select(-.row_id)
  writexl::write_xlsx(out_invalid, out_removed)
  cat("已写出被删除/不合法条目到：", out_removed, "\n")
  cat("被删除原因统计：\n")
  print(table(out_invalid$reason))
} else {
  cat("该删除的已经删除了(可能)。\n")
}

# ---------- 6. 便捷调试输出（可选） ----------
# 打印被删除的前 20 条以便快速查看
if (nrow(df_invalid) > 0) {
  cat("\n被删除的示例（前20行）：\n")
  print(head(out_invalid, 20))
}
